version: '3.8'
services:
  backend:
    container_name: news_aggregator_backend
    build:
      context: ./news_aggregator_backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./news_aggregator_backend:/app/backend
    networks:
      - app

  frontend:
    container_name: news_aggregator_frontend
    build:
      context: ./news_aggregator_frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./news_aggregator_frontend:/app/frontend
    networks:
      - app
    
  db:
    container_name: news_aggregator_mysql
    image: mysql:8
    ports:
      - "3306:3306"
    env_file:
      - ./env/mysql.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app
    restart: always

  phpmyadmin:
    container_name: news_aggregator_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - 81:80
    restart: always
    networks:
      - app

# Networks
networks:
  app:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local
